asyncapi: 2.0.0
info:
  title: Приложение оформления заказа
  version: '1.0.0'
  description: |
    Приложение оформления заказа/Event Collaboration
defaultContentType: application/json

channels:
  #  Регистрация пользователя
  gateway/registrationRequested:
    publish:
      message:
        tags:
          - name: user
        name: registrationRequested
        title: Пользователь запросил регистрацию
        payload:
          type: object
          properties:
            username:
              type: string
            firstName:
              type: string
            lastName:
              type: string
            email:
              type: string
            password:
              type: string
            phone:
              type: string
            address:
              type: string
        examples:
          - payload:
              username: vasya
              firstName: Василий
              lastName: Пупкин
              email: pupkin
              phone: '+71002003040'
              password: 'Jsd28xzd'
              address: 'ул Большая Филевская д 16 кв 19'
  user-service/userCreated:
    publish:
      message:
        name: UserCreated
        payload:
          type: object
          properties:
            id:
              type: integer
              format: int64
         examples:
          - payload:
              id: 42
  billing-service/accountCreated:
    publish:
      message:
        tags:
          - name: billing
        name: AccountCreated
        payload:
          type: object
          properties:
            accauntId:
              type: integer
        examples:
          - payload:
              accauntId: 1488
    subscribe:
      message:
        name: UserCreated
        payload:
          type: object
          properties:
            id:
              type: integer
              format: int64
        examples:
          - payload:
              id: 42
  notification-service/userCreated:
    subscribe:
      message:
        name: UserCreated
        payload:
          type: object
          properties:
            id:
              type: integer
              format: int64
        examples:
          - payload:
              id: 42
  notification-service/accountCreated:
    subscribe:
      message:
        tags:
          - name: billing
        name: AccountCreated
        payload:
          type: object
          properties:
            accauntId:
              type: integer
        examples:
          - payload:
              accauntId: 1488
  #Создание заказа
  gateway/createOrder:
    publish:
      message:
        tags:
          - name: order
        title: Создание заказа
        name: CreateOrder
        payload:
          type: object
          properties:
            userId:
              type: integer
            total:
              type: number
        examples:
          - payload:
              userId: 42
              total: 4200.42
  order-service/changeBalance:
    subscribe:
      message:
        tags:
          - name: order
        title: Создание заказа
        name: CreateOrder
        payload:
          type: object
          properties:
            userId:
              type: integer
            accauntId:
              type: integer
            total:
              type: number
        examples:
          - payload:
              userId: 42
              total: 4200.42
    publish:
      message:
        tags:
          - name: order
        title: Изменить баланс на аккаунте пользователя
        name: SpendMoney
        payload:
          type: object
          properties:
            orderId:
              type: integer
        examples:
          - payload:
              userId: 42
              total: 4200.42
  billing-service/spendMoney:
    subscribe:
      message:
        tags:
          - name: billing
        title: Изменить баланс на аккаунте пользователя
        name: ChangeBalance
        payload:
          type: object
          properties:
            orderId:
              type: integer
        examples:
          - payload:
              orderId: 42
              total: 4200.42
    publish:
      message:
        tags:
          - name: billing
        title: Результат транзакции
        name: TransactionResult
        payload:
          type: object
          properties:
            transactionId:
              type: integer
        examples:
          - payload:
              transactionId: 42
  order-service/createOrder:
    subscribe:
      message:
        tags:
          - name: order
        title: Результата транзакции
        name: TransactionResult
        payload:
          type: object
          properties:
            transactionId:
              type: integer
        examples:
          - payload:
              transactionId: 42
    publish:
      message:
        tags:
          - name: order
        title: Созданный заказ
        name: OrderCreated
        payload:
          type: object
          properties:
            orderId:
              type: integer
        examples:
          - payload:
              orderId: 42
  gateway/createdOrder:
    subscribe:
      message:
        tags:
          - name: order
        title: Созданный заказ
        name: OrderCreated
        payload:
          type: object
          properties:
            orderId:
              type: integer
        examples:
          - payload:
              orderId: 42
  notification-service/createdOrder:
    subscribe:
      message:
        tags:
          - name: order
        title: Созданный заказ
        name: OrderCreated
        payload:
          type: object
          properties:
            orderId:
              type: integer
        examples:
          - payload:
              orderId: 42
  notification-service/changeBalance:
    subscribe:
      message:
        tags:
          - name: order
        title: Инфо о транзакции
        name: TransactionResult
        payload:
          type: object
          properties:
            transactionId:
              type: integer
        examples:
          - payload:
              transactionId: 42
#              Пополнение счета
  gateway/accountDeposit:
    publish:
      message:
        tags:
          - name: account
        title: Пополнение счета пользователя
        name: Deposit
        payload:
          type: object
          properties:
            userId:
              type: integer
            total:
              type: number
        examples:
          - payload:
              userId: 42
              total: 4200.42
  billing-service/accountDeposit:
    subscribe:
      message:
        tags:
          - name: account
        title: Пополнение счета пользователя
        name: Deposit
        payload:
          type: object
          properties:
            userId:
              type: integer
            total:
              type: number
        examples:
          - payload:
              userId: 42
              total: 4200.42
    publish:
      message:
        tags:
          - name: account
        title: Измененный счет пользователя
        name: UpdateAccount
        payload:
          type: object
          properties:
            accountId:
              type: integer
        examples:
          - payload:
              accountId: 42
  notification-service/updateAccount:
    subscribe:
      message:
        tags:
          - name: account
        title: Измененный счет пользователя
        name: UpdateAccount
        payload:
          type: object
          properties:
            accountId:
              type: integer
        examples:
          - payload:
              accountId: 42
  gateway/updateAccount:
    subscribe:
      message:
        tags:
          - name: account
        title: Измененный счет пользователя
        name: UpdateAccount
        payload:
          type: object
          properties:
            accountId:
              type: integer
        examples:
          - payload:
              accountId: 42
  #Отправка письма
  notification-service/sendEmail:
    publish:
      message:
        tags:
          - name: email
        title: Отправка письма
        name: SendMail
        payload:
          type: object
          properties:
            email:
              type: string
              format: email
        examples:
          - payload:
              email: "vasya@pupkin.com"
#Компоненты
components:
  schemas:

    email:
      type: object
      properties:
        email:
          type: string
          format: email
        templateId:
          type: integer
        context:
          type: string
      required:
        - email
        - templateId
        - context
